#define BUILD_ENV_BME680
//#define BUILD_ENV_DHT22

#define BUILD_IMU_BNO08X
#define BUILD_IMU_MPU6050

#define BUILD_SYNC_TIME

#define BUILD_TICKER

#define BUILD_MOBILITY_TRACKED

/*
#define BUILD_ROBOTITO_OMNI
#define BUILD_ROBOTITO_APDS9960
#define BUILD_ROBOTITO_VL53RING
*/


